/**
 * This file was generated by the Jeddict
 */
package domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author charl
 */
@Entity
public class Education {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	private String name;

	private String startDate;

	private String educationLength;

	public Education() {
	}

	@OneToMany(mappedBy = "education")
	private List<Student> students;

	@ManyToMany(mappedBy = "educations")
	private List<Course> courses;

	public Education(String name, String startDate, String educationLength) {
		this.name = name;
		this.startDate = startDate;
		this.educationLength = educationLength;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEducationLength() {
		return this.educationLength;
	}

	public void setEducationLength(String educationLength) {
		this.educationLength = educationLength;
	}

	public List<Student> getStudents() {
		if (students == null) {
			students = new ArrayList<>();
		}
		return this.students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}

	public void addStudent(Student student) {
		getStudents().add(student);
		student.setEducation(this);
	}

	public void removeStudent(Student student) {
		getStudents().remove(student);
		student.setEducation(null);
	}

	public List<Course> getCourses() {
		if (courses == null) {
			courses = new ArrayList<>();
		}
		return this.courses;
	}

	public void setCourses(List<Course> courses) {
		this.courses = courses;
	}

	public void addCourse(Course course) {
		getCourses().add(course);
	}

	public void removeCourse(Course course) {
		getCourses().remove(course);
	}

}