/**
 * This file was generated by the Jeddict
 */
package domain;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author charl
 */
@Entity
public class Teacher {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	private String name;

	private String dateHired;

	public Teacher() {
	}

	@ManyToMany(cascade = CascadeType.PERSIST)
	private List<Course> courses;

    public void addToCourses(Course course) {
		courses.add(course);
		course.getTeachers().add(this);
    }

	public Teacher(String name, String dateHired) {
		this.name = name;
		this.dateHired = dateHired;
		courses = new ArrayList<Course>();
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDateHired() {
		return this.dateHired;
	}

	public void setDateHired(String dateHired) {
		this.dateHired = dateHired;
	}

	public List<Course> getCourses() {
		return this.courses;
	}
	
	public String test() {
		StringBuilder builder = new StringBuilder();
		for (Course course : courses) {
			builder.append(course.getSubject()+ ", ");
		}
		return builder.toString();
	}

	@Override
	public String toString() {
		return "Teacher " + getName() + " teaches : " + getCourses();
	}
	
	


}